version: "3.8"

services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: podbor
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: go_backend
    restart: always
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: podbor
      DB_PORT: "5432"
      OPENAI_API_KEY: secret
      ENV_FILE: /app/.env
    depends_on:
      - db
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/tern.conf:/app/tern.conf
      - ./backend/.env:/app/.env

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

volumes:
  db_data:
