version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: podbor_app
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: podbor_frontend
    ports:
      - "80:80"
    depends_on:
      - app

  db:
    image: postgres:14
    container_name: podbor_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: podbordb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: