server:
  port: "8080"

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  dbname: "podbordb"
  sslmode: "disable"

ai_service:
  api_key: "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"
